---
- hosts: localhost
  vars:
      docker_compose_version: "1.29.2"
      project_name : "WhatAMess"

  tasks:
    # Copy Docker Compose file
    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: ./
        
    # Pull Docker images and Start Containers using compose file
    - name: Run docker compose up command
      # shell: docker-compose up
      become: true
      docker_compose:
        project_src: ./
        state: present
        pull: yes